# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Battlestream < Formula
  desc "Hearthstone Battlegrounds stat tracker"
  homepage "https://github.com/beeblebrox/battlestream"
  version "0.14.0-beta"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/beeblebrox/battlestream/releases/download/v0.14.0-beta/battlestream_0.14.0-beta_darwin_amd64.tar.gz"
      sha256 "bf669a34277df0977ef0afa2719602e1f7fdd631b716c573ead493e4780662eb"

      define_method(:install) do
        bin.install "battlestream"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/beeblebrox/battlestream/releases/download/v0.14.0-beta/battlestream_0.14.0-beta_darwin_arm64.tar.gz"
      sha256 "0cc2b5063ce83754dfd3941c67f791a84c08d4471dcba809056d59a3b2e9f38b"

      define_method(:install) do
        bin.install "battlestream"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/beeblebrox/battlestream/releases/download/v0.14.0-beta/battlestream_0.14.0-beta_linux_amd64.tar.gz"
      sha256 "187ec3e62d93d23f9bb45a87c31b89e9b4d1e8162c6887127b86115fe248ca55"
      define_method(:install) do
        bin.install "battlestream"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/beeblebrox/battlestream/releases/download/v0.14.0-beta/battlestream_0.14.0-beta_linux_arm64.tar.gz"
      sha256 "76408578373b71e3e069e581ee90a33ef9ebbcf00b60a1931aa9660926ce9509"
      define_method(:install) do
        bin.install "battlestream"
      end
    end
  end

  test do
    system "#{bin}/battlestream", "version"
  end
end
